const recentBroadcasts = [{
  video_id: 8,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Congolese Franc Generic Steel Chicken',
  description: 'Nemo dolor sit sequi.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/I6yM8uM.png',
  thumbnail_url_2: 'https://i.imgur.com/NqXbLZj.png',
  thumbnail_url_3: 'https://i.imgur.com/SUS5P9i.png',
  thumbnail_url_4: 'https://i.imgur.com/cWQ8tGR.png',
  thumbnail_url_5: 'https://i.imgur.com/SPV2v29.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '23:39:30',
  view_count: 150,
  created_at: 1
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Plaza bandwidth',
  description: 'Omnis quis error nihil aspernatur.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Kb0ogF3.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/0zKL2Ov.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/QXps7wM.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/yQBzHki.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/1VExacK.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:48:19',
  view_count: 352,
  created_at: 1
},
{
  video_id: 12,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'SQL Russian Federation',
  description: 'Aut dicta ab eos velit.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Q1ASTgq.jpg',
  thumbnail_url_2: 'https://i.imgur.com/rZ3w4JB.jpg',
  thumbnail_url_3: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745603l.jpg',
  thumbnail_url_4: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745758l.jpg',
  thumbnail_url_5: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745108l.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '12:55:57',
  view_count: 102,
  created_at: 2
},
{
  video_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'streamline Architect',
  description: 'Sapiente pariatur aliquam quo animi excepturi nesciunt.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/dFqpmMv.png',
  thumbnail_url_2: 'https://i.imgur.com/vlaTV53.png',
  thumbnail_url_3: 'https://i.imgur.com/oP5VeGD.png',
  thumbnail_url_4: 'https://i.imgur.com/daPof5D.png',
  thumbnail_url_5: 'https://i.imgur.com/hrxibQx.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '17:58:33',
  view_count: 91,
  created_at: 2
},
{
  video_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'redefine Hungary',
  description: 'Quam est cupiditate veritatis qui repellendus deserunt officia commodi praesentium.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://vignette.wikia.nocookie.net/darksouls/images/e/e9/Dark-souls-ii-gameplay-screenshot-06.jpg/revision/latest/scale-to-width-down/640?cb=20130410233236',
  thumbnail_url_2: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_17.jpg',
  thumbnail_url_3: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_20.jpg',
  thumbnail_url_4: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_18.jpg',
  thumbnail_url_5: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_16.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '04:50:34',
  view_count: 55,
  created_at: 2
},
{
  video_id: 7,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'fuchsia bi-directional',
  description: 'Vel doloremque aut placeat itaque ut quam voluptatem.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/MidKpcy.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/xpWmJAf.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/Bb5FQ9d.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/KqHwWIj.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/K4Q8niX.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '03:42:04',
  view_count: 119,
  created_at: 3
},
{
  video_id: 10,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Outdoors deposit',
  description: 'Quia alias doloremque corrupti sit et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/UHVZeYx.png',
  thumbnail_url_2: 'https://i.imgur.com/NW90sLx.png',
  thumbnail_url_3: 'https://i.imgur.com/gnStqOa.png',
  thumbnail_url_4: 'https://i.imgur.com/2lRWk4P.png',
  thumbnail_url_5: 'https://i.imgur.com/6rf7s6R.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '18:51:37',
  view_count: 228,
  created_at: 3
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Auto Loan Account program',
  description: 'Voluptas nam quos perferendis sed quod repellat sequi provident quia.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '22:03:45',
  view_count: 367,
  created_at: 4
}];

const recentHighlights = [{
  video_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'matrices Intelligent',
  description: 'Numquam mollitia inventore voluptatum aspernatur numquam odio.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/RollingShot_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/SpinArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/Warcry_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/LungeArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/DarkKnight_sample_darksouls3-300x177.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '12:18:48',
  view_count: 398,
  created_at: 12
},
{
  video_id: 14,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'incentivize Reunion',
  description: 'Quod et autem exercitationem error consequatur.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/AjgdzRk.jpg',
  thumbnail_url_2: 'https://i.imgur.com/xGugOtM.jpg',
  thumbnail_url_3: 'https://i.imgur.com/mElLQY5.jpg',
  thumbnail_url_4: 'https://i.imgur.com/cvEeZiY.jpg',
  thumbnail_url_5: 'https://i.imgur.com/FJCrf9w.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '03:41:35',
  view_count: 392,
  created_at: 6
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Auto Loan Account program',
  description: 'Voluptas nam quos perferendis sed quod repellat sequi provident quia.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '22:03:45',
  view_count: 367,
  created_at: 4
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Plaza bandwidth',
  description: 'Omnis quis error nihil aspernatur.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Kb0ogF3.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/0zKL2Ov.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/QXps7wM.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/yQBzHki.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/1VExacK.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:48:19',
  view_count: 352,
  created_at: 1
},
{
  video_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'indexing payment',
  description: 'Veritatis velit dicta error sit et et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_001.jpg',
  thumbnail_url_2: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_003.jpg',
  thumbnail_url_3: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_005.jpg',
  thumbnail_url_4: 'https://i.imgur.com/WDveXJx.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/umlD9tO.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:35:07',
  view_count: 350,
  created_at: 7
},
{
  video_id: 15,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'mint green Auto Loan Account',
  description: 'Aperiam quos praesentium eligendi consequuntur quae molestias qui in blanditiis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://envul.com/ius/screenshots/subnautica/subnautica-wallpaper-2.png',
  thumbnail_url_2: 'https://envul.com/ius/screenshots/subnautica/subnautica-art-14.png',
  thumbnail_url_3: 'https://envul.com/ius/screenshots/subnautica/subnautica-poster-22.png',
  thumbnail_url_4: 'https://envul.com/ius/screenshots/subnautica/subnautica-gameplay-6.png',
  thumbnail_url_5: 'https://i.imgur.com/xEMchXo.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:58:40',
  view_count: 288,
  created_at: 10
},
{
  video_id: 10,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Outdoors deposit',
  description: 'Quia alias doloremque corrupti sit et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/UHVZeYx.png',
  thumbnail_url_2: 'https://i.imgur.com/NW90sLx.png',
  thumbnail_url_3: 'https://i.imgur.com/gnStqOa.png',
  thumbnail_url_4: 'https://i.imgur.com/2lRWk4P.png',
  thumbnail_url_5: 'https://i.imgur.com/6rf7s6R.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '18:51:37',
  view_count: 228,
  created_at: 3
},
{
  video_id: 13,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Investment Account Books',
  description: 'Officia hic voluptatem.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/vRFeaU3.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ZCQMSXJ.jpg',
  thumbnail_url_3: 'https://i.imgur.com/Cwurrst.jpg',
  thumbnail_url_4: 'https://i.imgur.com/GeHP2x6.jpg',
  thumbnail_url_5: 'https://i.imgur.com/mvlPYV4.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '07:02:52',
  view_count: 154,
  created_at: 12
}];

const popularClips = [{
  clip_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Nepalese Rupee out-of-the-box',
  description: 'Laborum architecto possimus et.',
  clipped_by: 'Brannon24',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://vignette.wikia.nocookie.net/darksouls/images/e/e9/Dark-souls-ii-gameplay-screenshot-06.jpg/revision/latest/scale-to-width-down/640?cb=20130410233236',
  thumbnail_url_2: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_17.jpg',
  thumbnail_url_3: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_20.jpg',
  thumbnail_url_4: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_18.jpg',
  thumbnail_url_5: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_16.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '14:51:25',
  view_count: 328,
  created_at: 12
},
{
  clip_id: 12,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Ball Consultant',
  description: 'Laborum quibusdam facilis pariatur.',
  clipped_by: 'Demetris82',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Q1ASTgq.jpg',
  thumbnail_url_2: 'https://i.imgur.com/rZ3w4JB.jpg',
  thumbnail_url_3: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745603l.jpg',
  thumbnail_url_4: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745758l.jpg',
  thumbnail_url_5: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745108l.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '21:43:23',
  view_count: 295,
  created_at: 11
},
{
  clip_id: 15,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'calculating Money Market Account',
  description: 'Eum possimus quo illum provident dicta debitis aspernatur.',
  clipped_by: 'Tyson_Considine',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://envul.com/ius/screenshots/subnautica/subnautica-wallpaper-2.png',
  thumbnail_url_2: 'https://envul.com/ius/screenshots/subnautica/subnautica-art-14.png',
  thumbnail_url_3: 'https://envul.com/ius/screenshots/subnautica/subnautica-poster-22.png',
  thumbnail_url_4: 'https://envul.com/ius/screenshots/subnautica/subnautica-gameplay-6.png',
  thumbnail_url_5: 'https://i.imgur.com/xEMchXo.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '04:16:38',
  view_count: 279,
  created_at: 7
},
{
  clip_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'withdrawal gold',
  description: 'Possimus fuga autem quia.',
  clipped_by: 'Drake93',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_001.jpg',
  thumbnail_url_2: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_003.jpg',
  thumbnail_url_3: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_005.jpg',
  thumbnail_url_4: 'https://i.imgur.com/WDveXJx.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/umlD9tO.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '11:51:58',
  view_count: 268,
  created_at: 10
},
{
  clip_id: 13,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Licensed Bedfordshire',
  description: 'Sit ut et eum laudantium voluptatem.',
  clipped_by: 'Kayley.Grady',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/vRFeaU3.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ZCQMSXJ.jpg',
  thumbnail_url_3: 'https://i.imgur.com/Cwurrst.jpg',
  thumbnail_url_4: 'https://i.imgur.com/GeHP2x6.jpg',
  thumbnail_url_5: 'https://i.imgur.com/mvlPYV4.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '21:34:49',
  view_count: 242,
  created_at: 7
},
{
  clip_id: 4,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Forward brand',
  description: 'Architecto est officia.',
  clipped_by: 'Sarah5',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/0RUxXTx.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/Dr0EgRv.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/KEouADT.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/tuWxihm.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/ukme2eO.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:39:10',
  view_count: 168,
  created_at: 7
},
{
  clip_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Executive Concrete',
  description: 'Quidem dicta molestiae repellat quo quam nihil et.',
  clipped_by: 'Rocio.Moore37',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '00:40:44',
  view_count: 117,
  created_at: 7
},
{
  clip_id: 14,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'infrastructures Networked',
  description: 'Officiis magnam nobis veniam.',
  clipped_by: 'Nya.Koelpin',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/AjgdzRk.jpg',
  thumbnail_url_2: 'https://i.imgur.com/xGugOtM.jpg',
  thumbnail_url_3: 'https://i.imgur.com/mElLQY5.jpg',
  thumbnail_url_4: 'https://i.imgur.com/cvEeZiY.jpg',
  thumbnail_url_5: 'https://i.imgur.com/FJCrf9w.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '16:58:16',
  view_count: 102,
  created_at: 1
}];

const allVideos = [{
  video_id: 1,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'redefine Hungary',
  description: 'Quam est cupiditate veritatis qui repellendus deserunt officia commodi praesentium.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://vignette.wikia.nocookie.net/darksouls/images/e/e9/Dark-souls-ii-gameplay-screenshot-06.jpg/revision/latest/scale-to-width-down/640?cb=20130410233236',
  thumbnail_url_2: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_17.jpg',
  thumbnail_url_3: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/dlc2_20.jpg',
  thumbnail_url_4: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_18.jpg',
  thumbnail_url_5: 'https://darksouls3.wiki.fextralife.com/file/Dark-Souls-3/gthumbnails/dlc2_16.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '04:50:34',
  view_count: 55,
  created_at: 2
},
{
  video_id: 2,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Auto Loan Account program',
  description: 'Voluptas nam quos perferendis sed quod repellat sequi provident quia.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer2_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/Pursuer1_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/ArmoredBeast_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/Undead_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/ReadyStanceArt_sample_darksouls3-300x169.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '22:03:45',
  view_count: 367,
  created_at: 4
},
{
  video_id: 3,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'matrices Intelligent',
  description: 'Numquam mollitia inventore voluptatum aspernatur numquam odio.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://fextralife.com/wp-content/uploads/2015/08/RollingShot_sample_darksouls3-300x169.jpg',
  thumbnail_url_2: 'https://fextralife.com/wp-content/uploads/2015/08/SpinArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_3: 'https://fextralife.com/wp-content/uploads/2015/08/Warcry_sample_darksouls3-300x169.jpg',
  thumbnail_url_4: 'https://fextralife.com/wp-content/uploads/2015/08/LungeArt_sample_darksouls3-300x169.jpg',
  thumbnail_url_5: 'https://fextralife.com/wp-content/uploads/2015/08/DarkKnight_sample_darksouls3-300x177.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '12:18:48',
  view_count: 398,
  created_at: 12
},
{
  video_id: 4,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Mouse Games',
  description: 'Velit repudiandae dicta veritatis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/0RUxXTx.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/Dr0EgRv.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/KEouADT.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/tuWxihm.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/ukme2eO.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:26:46',
  view_count: 112,
  created_at: 5
},
{
  video_id: 5,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'indexing payment',
  description: 'Veritatis velit dicta error sit et et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_001.jpg',
  thumbnail_url_2: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_003.jpg',
  thumbnail_url_3: 'https://gematsu.com/gallery/albums/dark-souls-iii/january-27-2016/Dark-Souls-III_2016_01-27-16_005.jpg',
  thumbnail_url_4: 'https://i.imgur.com/WDveXJx.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/umlD9tO.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:35:07',
  view_count: 350,
  created_at: 7
},
{
  video_id: 6,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'Plaza bandwidth',
  description: 'Omnis quis error nihil aspernatur.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Kb0ogF3.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/0zKL2Ov.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/QXps7wM.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/yQBzHki.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/1VExacK.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '08:48:19',
  view_count: 352,
  created_at: 1
},
{
  video_id: 7,
  user_name: 'A_Seagull',
  game_name: 'Dark Souls III',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dark%20Souls%20III-40x56.jpg',
  title: 'fuchsia bi-directional',
  description: 'Vel doloremque aut placeat itaque ut quam voluptatem.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/MidKpcy.jpg?1',
  thumbnail_url_2: 'https://i.imgur.com/xpWmJAf.jpg?1',
  thumbnail_url_3: 'https://i.imgur.com/Bb5FQ9d.jpg?1',
  thumbnail_url_4: 'https://i.imgur.com/KqHwWIj.jpg?1',
  thumbnail_url_5: 'https://i.imgur.com/K4Q8niX.jpg?1',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '03:42:04',
  view_count: 119,
  created_at: 3
},
{
  video_id: 8,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Congolese Franc Generic Steel Chicken',
  description: 'Nemo dolor sit sequi.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/I6yM8uM.png',
  thumbnail_url_2: 'https://i.imgur.com/NqXbLZj.png',
  thumbnail_url_3: 'https://i.imgur.com/SUS5P9i.png',
  thumbnail_url_4: 'https://i.imgur.com/cWQ8tGR.png',
  thumbnail_url_5: 'https://i.imgur.com/SPV2v29.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '23:39:30',
  view_count: 150,
  created_at: 1
},
{
  video_id: 9,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'purple bluetooth',
  description: 'Sunt voluptatem et numquam et et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/2E0RsZz.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ibDLj60.jpg',
  thumbnail_url_3: 'https://i.imgur.com/wEBv9tt.jpg',
  thumbnail_url_4: 'https://i.imgur.com/sR4KYI9.png',
  thumbnail_url_5: 'https://i.imgur.com/nk0Uoys.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '22:23:17',
  view_count: 36,
  created_at: 8
},
{
  video_id: 10,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'Outdoors deposit',
  description: 'Quia alias doloremque corrupti sit et.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/UHVZeYx.png',
  thumbnail_url_2: 'https://i.imgur.com/NW90sLx.png',
  thumbnail_url_3: 'https://i.imgur.com/gnStqOa.png',
  thumbnail_url_4: 'https://i.imgur.com/2lRWk4P.png',
  thumbnail_url_5: 'https://i.imgur.com/6rf7s6R.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '18:51:37',
  view_count: 228,
  created_at: 3
},
{
  video_id: 11,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'streamline Architect',
  description: 'Sapiente pariatur aliquam quo animi excepturi nesciunt.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/dFqpmMv.png',
  thumbnail_url_2: 'https://i.imgur.com/vlaTV53.png',
  thumbnail_url_3: 'https://i.imgur.com/oP5VeGD.png',
  thumbnail_url_4: 'https://i.imgur.com/daPof5D.png',
  thumbnail_url_5: 'https://i.imgur.com/hrxibQx.png',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '17:58:33',
  view_count: 91,
  created_at: 2
},
{
  video_id: 12,
  user_name: 'A_Seagull',
  game_name: 'Overwatch',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-52x72.jpg',
  title: 'SQL Russian Federation',
  description: 'Aut dicta ab eos velit.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/Q1ASTgq.jpg',
  thumbnail_url_2: 'https://i.imgur.com/rZ3w4JB.jpg',
  thumbnail_url_3: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745603l.jpg',
  thumbnail_url_4: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745758l.jpg',
  thumbnail_url_5: 'https://www.overclock3d.net/gfx/articles/2016/05/06071745108l.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '12:55:57',
  view_count: 102,
  created_at: 2
},
{
  video_id: 13,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'Investment Account Books',
  description: 'Officia hic voluptatem.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/vRFeaU3.jpg',
  thumbnail_url_2: 'https://i.imgur.com/ZCQMSXJ.jpg',
  thumbnail_url_3: 'https://i.imgur.com/Cwurrst.jpg',
  thumbnail_url_4: 'https://i.imgur.com/GeHP2x6.jpg',
  thumbnail_url_5: 'https://i.imgur.com/mvlPYV4.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '07:02:52',
  view_count: 154,
  created_at: 12
},
{
  video_id: 14,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'incentivize Reunion',
  description: 'Quod et autem exercitationem error consequatur.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://i.imgur.com/AjgdzRk.jpg',
  thumbnail_url_2: 'https://i.imgur.com/xGugOtM.jpg',
  thumbnail_url_3: 'https://i.imgur.com/mElLQY5.jpg',
  thumbnail_url_4: 'https://i.imgur.com/cvEeZiY.jpg',
  thumbnail_url_5: 'https://i.imgur.com/FJCrf9w.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '03:41:35',
  view_count: 392,
  created_at: 6
},
{
  video_id: 15,
  user_name: 'A_Seagull',
  game_name: 'Subnautica',
  game_box_art_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Subnautica-40x56.jpg',
  title: 'mint green Auto Loan Account',
  description: 'Aperiam quos praesentium eligendi consequuntur quae molestias qui in blanditiis.',
  clipped_by: 'A_Seagull',
  url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  thumbnail_url_1: 'https://envul.com/ius/screenshots/subnautica/subnautica-wallpaper-2.png',
  thumbnail_url_2: 'https://envul.com/ius/screenshots/subnautica/subnautica-art-14.png',
  thumbnail_url_3: 'https://envul.com/ius/screenshots/subnautica/subnautica-poster-22.png',
  thumbnail_url_4: 'https://envul.com/ius/screenshots/subnautica/subnautica-gameplay-6.png',
  thumbnail_url_5: 'https://i.imgur.com/xEMchXo.jpg',
  user_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  game_url: 'https://www.youtube.com/watch?v=oHg5SJYRHA0',
  duration: '20:58:40',
  view_count: 288,
  created_at: 10
}];


module.exports.recentBroadcasts = recentBroadcasts;
module.exports.recentHighlights = recentHighlights;
module.exports.popularClips = popularClips;
module.exports.allVideos = allVideos;